name: iiot-anomaly-detection
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.23.5
  - pandas=1.5.3
  - matplotlib=3.7.2
  - scikit-learn=1.3.0
  - seaborn=0.12.2
  - librosa=0.10.0
  - jupyterlab=3.6.5
  - pyarrow=19.0.1
  - fastparquet=2024.11.0
  - pip
  - pip:
      - dash
      - thingspeak
      - pytest