name: CI Workflow

on:
  push:
    branches:
      - main  # Run on push to main branch
  pull_request:
    branches:
      - main  # Run on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Ensure environment.yml exists
      - name: Check for environment.yml
        run: |
          if [ ! -f environment.yml ]; then
            echo "environment.yml not found"; exit 1;
          fi

      # Step 3: Cache Conda environment
      - name: Cache Conda environment
        uses: actions/cache@v3
        with:
          path: ~/conda-envs
          key: conda-env-${{ hashFiles('environment.yml') }}  # Cache key based on environment.yml hash
          restore-keys: |
            conda-env-

      # Step 4: Set up Conda
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9  # Match the Python version in environment.yml
          auto-update-conda: true  # Ensure Conda is up to date

      # Step 5: Create or Update Conda Environment Using --prune
      - name: Create or Update Conda Environment
        run: |
          mkdir -p ~/conda-envs
          conda env update -p ~/conda-envs/iiot-anomaly-detection --file environment.yml --prune
          conda list -p ~/conda-envs/iiot-anomaly-detection  # List installed packages for debugging

      # Step 6: Verify pytest installation
      - name: Verify pytest installation
        run: |
          conda run -p ~/conda-envs/iiot-anomaly-detection pytest --version  # Check pytest version

      # Step 7: Run tests
      - name: Run tests
        run: |
          conda run -p ~/conda-envs/iiot-anomaly-detection pytest