   name: CI Workflow

   on:
     push:  # Trigger CI workflow on push
       branches:
         - main
     pull_request:  # Also trigger on pull requests targeting main
       branches:
         - main

   jobs:
     test:
       runs-on: ubuntu-latest

       steps:
         # Step 1: Checkout the repository
         - name: Checkout code
           uses: actions/checkout@v3

         # Step 2: Set up Python and Conda
         - name: Set up Python
           uses: conda-incubator/setup-miniconda@v2
           with:
             python-version: 3.9  # Python version defined in Conda environment
             environment-file: environment.yml  # Use environment.yml
             activate-environment: iiot-anomaly-detection

         # Step 3: Install pip dependencies (if any)
         - name: Install pip dependencies
           run: pip install -r requirements.txt || true

         # Step 4: Run Tests
         - name: Run tests
           run: |
             pytest  # Run all test cases